### ISSUE TITLE
PySimpleGUI not found

### ISSUE THREAD

**Issue by rmadhok** [benjaminvatterj/JobMarketTracker#7]
Thanks for this resource. When I run main.py it says "ModuleNotFoundError: No module names 'PySimpleGUI'". I have installed all the requirements as noted from the .txt. Any idea what the issue is? I am using python 3.7.3.
Thanks

**Comment by benjaminvatterj** [comment]
Hi,

Could you post the full error message with its stack trace? Also the outcome of pip freeze. It is probably just an issue in the installation of the pysimplegui library.

**Comment by rmadhok** [comment]
Thanks for the quick response. Here is the trace:

> Traceback (most recent call last):
>   File "main.py", line 54, in <module>
>     available_actions[action](args)
>   File "main.py", line 11, in launch_gui
>     from JMTracker import Tracker
>   File "/Users/rmadhok/Dropbox/job_market/apps/JobMarketTracker/JMTracker/__init__.py", line 3, in <module>
>     from .settings import settings, input_option_settings
>   File "/Users/rmadhok/Dropbox/job_market/apps/JobMarketTracker/JMTracker/settings.py", line 4, in <module>
>     from JMTracker.scrapper import AJOScrapper
>   File "/Users/rmadhok/Dropbox/job_market/apps/JobMarketTracker/JMTracker/scrapper.py", line 6, in <module>
>     import PySimpleGUI as sg
> ModuleNotFoundError: No module named 'PySimpleGUI'

And from pip freeze
(base) Raahils-Air:JobMarketTracker rmadhok$ pip freeze
beautifulsoup4==4.11.1
certifi==2022.6.15.1
chardet==4.0.0
charset-normalizer==2.1.1
et-xmlfile==1.1.0
humanize==4.3.0
idna==2.10
importlib-metadata==4.12.0
lxml==4.9.1
meson==0.51.2
numpy==1.21.6
openpyxl==3.0.10
pandas==1.3.5
PySimpleGUI==4.60.3
python-dateutil==2.8.2
pytz==2022.2.1
requests==2.28.1
six==1.16.0
soupsieve==2.3.2.post1
typing_extensions==4.3.0
urllib3==1.26.12
xlrd==2.0.1
zipp==3.8.1

Thanks

**Comment by benjaminvatterj** [comment]
That’s strange. It’s definitely and issue with the pysimplegui installation and not this library. Do you have multiple versions of python installed or are you using virtual environments? It might be that pip is linked to a different path then your default python path. Try doing “python -m pip freeze” and see if it looks the same. Alternatively try reinstalling pysimplegui with “python -m pip install”. Then just open a simple python terminal and see whether you can import pysimplegui. 

Best,
Ben.

**Comment by rmadhok** [comment]
The last suggestion (python -m pip install) worked. Thanks!
